-- 
-- SCRIPT DE INICIALIZAÇÃO - COMPROMISSO SMART EDUCATION
-- Cole este script no SQL Editor do Supabase e clique em RUN.
--

-- 1. Tabela de Perfis (Profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  name TEXT,
  email TEXT,
  profile_type TEXT CHECK (profile_type IN ('etec', 'uni', 'teacher')),
  institution TEXT,
  course TEXT,
  interests TEXT,
  is_financial_aid_eligible BOOLEAN DEFAULT FALSE,
  last_access TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Ativar Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acesso (Policies)
CREATE POLICY "Usuários podem ver seu próprio perfil" 
  ON public.profiles FOR SELECT 
  USING (auth.uid() = id);

CREATE POLICY "Usuários podem atualizar seu próprio perfil" 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id);

CREATE POLICY "Inserção pública no cadastro" 
  ON public.profiles FOR INSERT 
  WITH CHECK (TRUE);

-- 4. Tabela de Avisos (Announcements)
CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  priority TEXT CHECK (priority IN ('low', 'medium', 'high')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Qualquer um pode ver avisos" 
  ON public.announcements FOR SELECT 
  USING (TRUE);

CREATE POLICY "Apenas professores inserem avisos" 
  ON public.announcements FOR INSERT 
  WITH CHECK (auth.jwt() ->> 'role' = 'teacher' OR auth.jwt() ->> 'role' = 'admin');
